### PR TITLE
fix(index): return `undefined` on error instead of `null`

### LINKED ISSUE #132: safeParse returns null rather than undefined, but null is a valid JSON value.
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

`safeParse` returns null if parsing fails, but it should return undefined, because JSON.parse will never return undefined, but it will return null. `'null'` is valid JSON, `'undefined'` will throw. With it returning null, there is no way to tell that parsing failed. 

You had one job! 😢 Ok, technically that wasn't your one job. But now I guess I'll have to fork it just to change that.

### PR DESCRIPTION
**Pull request by Fdawgs**
closes #132 

This is a breaking change so it'd be great to combine this with https://github.com/fastify/secure-json-parse/issues/72

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -113,7 +113,7 @@ function safeParse (text, reviver) {
   try {
     return _parse(text, reviver, { safe: true })
   } catch (_e) {
```
Comment (gurgunday) [inline index.js:115]:
```suggestion
  } catch {
```

**Review by gurgunday — COMMENTED** [review]
Why undefined instead of null? Is there a reason?

Isn't it better to keep the return type 'object' all the time? Or is that specifically what you don't want? :)

**Review by gurgunday — APPROVED** [review]
Oh I see, makes sense to me as `null` is valid JSON

File: index.js (hunk 1 above)
Comment (Fdawgs) [reply index.js:115]: Can't remove, see https://github.com/fastify/secure-json-parse/pull/129 :(

**Review by Eomm — APPROVED** [review]

**Review by metcoder95 — APPROVED** [review]
